apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rgdev
resources:
- deployment.yaml
- namespace.yaml
- sealedsecret.yaml
configMapGenerator:
- name: example-configmap
  files:
    - application.properties